# Generated by Django 6.0.6 on 2026-06-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('customer', 'month', 'year')},
        ),
    ]
