# Generated by Django 6.0.6 on 2026-06-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
